### ISSUE TITLE
no picture saved on camera when trigger file added

### ISSUE THREAD

**Issue by mailbaoer** [touchbyte/GPhoto2Framework#1]
**Describe the bug**

no picture saved on camera when use `gp_camera_wait_for_event`

**Name the camera**
Canon 5D Mrk IV

**libgphoto2 and gphoto2 version**
2.5.26

**To Reproduce**
use `gp_camera_wait_for_event` method to receive `GP_EVENT_FILE_ADDED` event, then download the caputre file to my phone, but the camera has no file saved, how can I trigger with `GP_EVENT_FILE_ADDED` with file saved on camera correctily, Thank you very much!

**Comment by mailbaoer** [comment]
I have found the way to save picture on sd card， just set `gp_setting_set(camera, context, 'card')` it worked!

**Comment by SiuyuenChow** [comment]
Hi,

Could you please tell me, when using gp_camera_wait_for_event, can the camera take pictures normally?
I can't take a picture, so I can't receive GP_EVENT_FILE_ADDED

I'd like to consult you.

Thanks

**Comment by mailbaoer** [comment]
yes， we use canon and nikon tested，both can take pictures and receive GP_EVENT_FILE_ADDED

**Comment by SiuyuenChow** [comment]
> yes， we use canon and nikon tested，both can take pictures and receive GP_EVENT_FILE_ADDED


how can u do it？

while (1) {
gp_camera_wait_for_event(camera, 1000, &eType, &dData, context);
}

I found that when I polled the gp_camera_wait_for_event method, only this GP_EVENT_FILE_ADDED was not accepted.
The EOS 6D camera screen shows BUSY every time.

My device is EOS 6D
By the way, I found that polling gp_camera_wait_for_event causes the camera to fail to take a picture

**Comment by SiuyuenChow** [comment]
This is my code:

self.protocol = @"ptpip";
self.cameraModel = @"Canon EOS (WLAN)";
NSString *connectionStr = [NSString stringWithFormat:@"%@:%@",self.protocol,cameraIP];
int ret,indexCamera,indexPort;
CameraAbilitiesList *abilities;
CameraAbilities a;

GPPortInfoList *portinfolist = NULL;
GPPortInfo pi;

gp_log_add_func(GP_LOG_ERROR, errordumper, NULL);
gp_log_add_func(GP_LOG_DEBUG, logdumper, NULL);

context = gp_context_new();

gp_camera_new (&camera);

gp_abilities_list_new (&abilities);

ret = gp_abilities_list_load (abilities, context);

indexCamera = gp_abilities_list_lookup_model (abilities, [self.cameraModel UTF8String]);

if (indexCamera>=0) {

gp_abilities_list_get_abilities (abilities, indexCamera, &a);

gp_camera_set_abilities (camera, a);
}

gp_port_info_list_new (&portinfolist);

ret = gp_port_info_list_load (portinfolist);

ret = gp_port_info_list_count (portinfolist);

indexPort = gp_port_info_list_lookup_path (portinfolist, [connectionStr UTF8String]);
if (indexPort>=0) {

gp_port_info_list_get_info (portinfolist, indexPort, &pi);
gp_camera_set_port_info (camera, pi);
}

gp_port_info_list_free(portinfolist);
gp_abilities_list_free(abilities);

gp_setting_set("ptpip", "hostname", "test");

ret = gp_camera_init (camera, context);
if (ret == GP_OK) {
while (1) {
retval = gp_camera_wait_for_event (camera, 1, &evttype, &evtdata, context);
}
}

**Comment by SiuyuenChow** [comment]
The connection was successful,

sleep(10);

call

while (1) {
int ret = gp_camera_wait_for_event(newCamera, 10, &evttype, &evtdata, ctx);
}

In sleep (10); So that's 10 seconds. I pressed the shutter on my camera, so let's say I pressed the shutter 4 times in 10 seconds to take a picture

GP_CAMERA_WAIT_FOR_EVENT returns GP_EVENT_FILE_Added four times

But when you press the shutter after sleep(10) to take a picture, you never get back to GP_EVENT_FILE_ADDED

I can only get GP_EVENT_FILE_ADDED if I turn off the WiFi inside the camera and turn it back on again

It's not quite clear why that is.
