### ISSUE TITLE
The file cannot be updated

### ISSUE THREAD

**Issue by SiuyuenChow** [touchbyte/GPhoto2Framework#2]
HI
I have a question to ask you.

The first to use
-(int)listAlFiles:(const char*)folder foundfile:(int*)foundfile files:(NSMutableArray*)files
Get all the folders and files

Then manually add a new folder to the camera and re-click Get -(int) ListAlFiles :(const char*) Folder FoundFile :(int*) FoundFile :(NSMutableArray*) Files
The newly added folder and files cannot be retrieved at this time

By the way, could the demo include some examples of getting a preview and polling for a new file?

thanks

**Comment by hholtmann** [comment]
- libgphoto caches the file system. So if you add items, you need to reset the cache
- waitforevent works only on supported camera models. When you call waitforevent and the camera does not switch from playback to record mode, ist most likely does not support taking photos tethered.
- I would recommend you use gphoto2 over USB to find out what your camera supports.

**Comment by SiuyuenChow** [comment]
> * libgphoto caches the file system. So if you add items, you need to reset the cache
> * waitforevent works only on supported camera models. When you call waitforevent and the camera does not switch from playback to record mode, ist most likely does not support taking photos tethered.
> * I would recommend you use gphoto2 over USB to find out what your camera supports.

thanks，
And by the way, another question came up,

When polling for a new file, the camera has pressed the shutter to take a picture, the number of photos has not been added, nor has it received a return from GP_EVENT_FILE_ADDED. The camera seems to be busy all the time, and the camera model is EOS 6D

while (1) {
retval = gp_camera_wait_for_event (camera, 1, &evttype, &evtdata, context);
}

**Comment by hholtmann** [comment]
You will not get a number or something like that. The camera will for each added file report a separate event.

**Comment by SiuyuenChow** [comment]
> You will not get a number or something like that. The camera will for each added file report a separate event.

Yes, but I haven't received it for a long time
Modeled on https://github.com/gphoto/libgphoto2 example to write, using gp_camera_wait_for_event can let a camera to take pictures, don't know how to solve

I am not very familiar with the GPhoto2 framework, and I do not know much about libgphoto2.

Want to consult

It would be nice if we had this example in the demo of the Gphoto 2Framework

thanks

**Comment by SiuyuenChow** [comment]
here is the log,when i use gp_camera_trigger_capture(camera, context);


camera_trigger_capture
Triggering capture to , autofocus=0
camera_trigger_canon_eos_capture
prepare_capture
preparing EOS capture...
Sending PTP_OC 0x9114 (EOS_SetRemoteMode) (0x1) request...
End of stream after reading 0 bytes of ptpipheader
End of stream after reading 0 bytes of ptpipheader
Reading PTP_OC 0x9114 (EOS_SetRemoteMode) response...
End of stream after reading 0 bytes of ptpipheader
End of stream after reading 0 bytes of ptpipheader
End of stream after reading 0 bytes of ptpipheader
End of stream after reading 0 bytes of ptpipheader
'ptp_canon_eos_setremotemode(params, 1)' failed: PTP General Error (0x2002)
'ptp_canon_eos_setremotemode(params, 1)' failed: PTP General Error (0x2002)
Sending PTP_OC 0x9116 (EOS_GetEvent) request...
End of stream after reading 0 bytes of ptpipheader
End of stream after reading 0 bytes of ptpipheader
Reading PTP_OC 0x9116 (EOS_GetEvent) data...
End of stream after reading 0 bytes of ptpipheader
End of stream after reading 0 bytes of ptpipheader
End of stream after reading 0 bytes of ptpipheader
End of stream after reading 0 bytes of ptpipheader
Sending PTP_OC 0x9128 (EOS_RemoteReleaseOn) (0x1,0x0) request...
End of stream after reading 0 bytes of ptpipheader
End of stream after reading 0 bytes of ptpipheader
Reading PTP_OC 0x9128 (EOS_RemoteReleaseOn) response...
End of stream after reading 0 bytes of ptpipheader
End of stream after reading 0 bytes of ptpipheader
End of stream after reading 0 bytes of ptpipheader
End of stream after reading 0 bytes of ptpipheader
'ptp_canon_eos_remotereleaseon (params, 1, 0)' failed: Canon EOS Half-Press failed (0x2002: PTP General Error)
'ptp_canon_eos_remotereleaseon (params, 1, 0)' failed: Canon EOS Half-Press failed (0x2002: PTP General Error)
Canon EOS Half-Press failed (0x2002: PTP General Error)
Canon EOS Half-Press failed (0x2002: PTP General Error)

*** Contexterror ***              
Canon EOS Half-Press failed (0x2002: PTP General Error)
'camera->functions->trigger_capture (camera, context)' failed: -1
'camera->functions->trigger_capture (camera, context)' failed: -1

**Comment by SiuyuenChow** [comment]
info update.

while (1) {
gp_camera_wait_for_event(camera, 1000, &eType, &dData, context);
}

I found that when I polled the gp_camera_wait_for_event method, only this GP_EVENT_FILE_ADDED was not accepted.
The EOS 6D camera screen shows BUSY every time.

**Comment by SiuyuenChow** [comment]
hello again & ask a question again

Camera model: EOS 200DII
When I call gp_camera_wait_for_event, I take the picture and return the following

Downloading capt0000.jpg / 0...
Downloading capt0001.jpg / 0...
Downloading capt0002.jpg / 0...

gphoto2——set-config capturetarget = 1 ----> like this? -----> gp_setting_set("gphoto2", "--set-config", "capturetarget=1");

thanks

**Comment by SiuyuenChow** [comment]
hello again

If it's convenient, can you give me some guidance?

Or can you write a demo of gp_camera_wait_for_event here? I can refer to your way here.

thank you

Siu

**Comment by SiuyuenChow** [comment]
Problem solved

**Comment by mailbaoer** [comment]
👍
